name: CI

on: [ push, pull_request ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cpplint
        run: pip3 install cpplint
      - name: Lint C++ files
        run: |
          cd src
          echo "filter=-legal/copyright,-readability/todo, -build/namespaces_literals,-build/include_subdir, -build/include_what_you_use, -whitespace/indent_namespace
                linelength=120" > CPPLINT.cfg
          cpplint --recursive .
